[package]
name = "saya-lang-japanese"
version = "0.1.0"
edition = "2024"

[dependencies]
saya-core = { path = "../../crates/saya-core" }
unicode-normalization = { version = "0.1" }
serde_json = { workspace = true }
